Repository jolibrain/joliGEN, pull requests merged in 2022-09, with the labels that each got.

#250 fix: temporal discriminator image loading + skip temporal weights upon resume
  data/temporal_dataset.py
  models/base_model.py
  models/modules/projected_d/discriminator.py
  tests/test_run_semantic_mask_online.py
Labels: model:discriminator

#253 feat : option for jit model exporting
  models/base_model.py
  options/train_options.py
Labels: type:export

#256 feat: support for amp on forward ops
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
  options/base_options.py
Labels: gpu

#257 chore: torch 1.12.1 requirements
  requirements.txt
Labels: type:docker

#254 Fix sv network
  train.py
Labels: type:export

#252 feat: backward while computing MSE criterion loss
  models/base_model.py
  tests/test_run_semantic_mask_online.py
Labels: nn:loss

#259 chore: removing frozen versions in requirements
  requirements.txt
Labels: dependencies

#261 chore: add new option category for classification network
  options/base_options.py
Labels: documentation, api, ready-for-review

#264 feat(server): add commit number in swagger documentation
  server/joligan_api.py
Labels: ready-for-review

#262 chore: refactor to create base_gan_model
  models/base_gan_model.py
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
Labels: refactor, ready-for-review

#266 fix: get schema should not compute base_gan_model
  models/__init__.py
Labels: documentation
