Repository jolibrain/joliGEN, pull requests merged in 2022-12, with the labels that each got.

#322 fix: option to not set device when parsing json config file
  options/base_options.py
  scripts/gen_single_image.py
Labels: bug

#312 ResNet and Mobile ResNet with Attention mecanism for diffusion models
  models/base_model.py
  models/diffusion_networks.py
  models/modules/diffusion_generator.py
  models/modules/diffusion_utils.py
  models/modules/resnet_architecture/resnet_generator_diff.py
  models/modules/segformer/segformer_diff.py
  models/modules/unet_generator_attn/unet_generator_attn.py
  models/palette_model.py
  options/base_options.py
Labels: model:generator, alg:diffusion

#321 chore: support for relative paths in sanitize_paths
  data/online_creation.py
  data/unaligned_labeled_mask_online_dataset.py
Labels: data:dataloader

#303 feat: export for unet_mha
  models/base_model.py
  models/modules/unet_generator_attn/unet_generator_attn.py
  scripts/export_onnx_model.py
Labels: type:export, ready-for-review

#307 feat: add SRC and hDCE losses 2203.01532
  models/cut_model.py
  models/modules/NCE/SRC.py
  models/modules/NCE/base_NCE.py
  models/modules/NCE/hDCE.py
  models/modules/NCE/monce.py
  models/modules/NCE/patchnce.py
  models/modules/NCE/sinkhorn.py
  models/monce.py
Labels: nn:loss

#326 fix: multimodal GAN requires retain_graph for now
  models/base_model.py
Labels: alg:gan

#327 fix: forward_gan and compute_temporal_fake defined twice
  models/base_gan_model.py
  models/base_model.py
Labels: bug

#328 feat: depth prediction and depth discriminator
  models/base_gan_model.py
  models/cut_model.py
  models/gan_networks.py
  models/modules/utils.py
  options/base_options.py
  tests/test_run_nosemantic.py
Labels: model:discriminator

#330 fix: onnx export
  models/base_model.py
  scripts/export_onnx_model.py
  train.py
  util/export/onnx.py
Labels: bug, type:export

#332 feat: tf32 support (with Ampere GPUs)
  options/base_options.py
  train.py
Labels: gpu

#331 fix: support for no mask in B domain
  data/unaligned_labeled_mask_dataset.py
  data/unaligned_labeled_mask_online_dataset.py
Labels: bug

#334 fix: remove eval mode for export
  models/base_model.py
Labels: bug, type:export

#333 chore: diffusion model generation inpainting from crops
  scripts/gen_single_image_diffusion.py
Labels: type:inference

#325 chore: builder for segformer to remove mmcv
  models/configs/segformer/segformer_config_b0.json
  models/configs/segformer/segformer_config_b1.json
  models/configs/segformer/segformer_config_b2.json
  models/configs/segformer/segformer_config_b3.json
  models/configs/segformer/segformer_config_b4.json
  models/configs/segformer/segformer_config_b5.json
  models/diffusion_networks.py
  models/modules/projected_d/projector.py
  models/modules/segformer/backbone.py
  models/modules/segformer/builder_from_scratch.py
  models/modules/segformer/config.py
  models/modules/segformer/decode_head.py
  models/modules/segformer/segformer_diff.py
  models/modules/segformer/segformer_generator.py
  models/modules/segformer/segformer_head.py
  models/modules/segformer/shape_convert.py
  models/modules/segformer/utils.py
  options/base_options.py
  requirements.txt
Labels: refactor

#337 chore: avoid midas 3.1 error
  models/modules/utils.py
Labels: type:depedencies
