Repository jolibrain/joliGEN, pull requests merged in 2022-03, with the labels that each got.

#123 feat: option to use a different f_s for domain B
  models/cut_semantic_mask_model.py
  models/cycle_gan_semantic_mask_model.py
  options/train_options.py
Labels: nn:semantic

#133 feat(server): add synchronous training
  server/joligan_api.py
  server/run.sh
Labels: api

#131 feat: pretrained segformer backbone (mit) as feature extractor for projected D
  models/modules/projected_d/discriminator.py
  models/modules/projected_d/projector.py
  models/networks.py
  options/base_options.py
Labels: model:discriminator

#144 fix: new options names for unaligned_labeled_mask
  data/unaligned_labeled_mask_dataset.py
Labels: bug

#141 feat(server): group options into categories
  options/base_options.py
Labels: api

#142 feat: use label 0 in domain B for object removal
  models/cut_semantic_mask_model.py
  options/train_options.py
Labels: alg:cut, nn:semantic

#143 feat: load segformer torchscript weights
  models/modules/projected_d/projector.py
Labels: model:discriminator

#136 refactor: opt use for network creation
  data/base_dataset.py
  models/cut_model.py
  models/cut_semantic_mask_model.py
  models/cut_semantic_model.py
  models/cycle_gan_model.py
  models/cycle_gan_semantic_mask_model.py
  models/cycle_gan_semantic_model.py
  models/modules/attn_network.py
  models/modules/cut_networks.py
  models/modules/resnet_architecture/resnet_generator.py
  models/modules/segformer/segformer_generator.py
  models/modules/stylegan_networks.py
  models/modules/utils.py
  models/networks.py
  scripts/export_jit_model.py
  scripts/export_onnx_model.py
Labels: refactor

#145 Feat load pretrained f s
  models/modules/utils.py
  models/networks.py
  options/base_options.py
Labels: nn:semantic

#148 chore: requirements update
  requirements.txt
Labels: type:depedencies

#150 chore: small unit tests cleanup
  scripts/run_tests.sh
  tests/test_run_horse2zebra.py
Labels: type:tests

#149 chore: initial joliGAN docker with server
  README.md
  docker/Dockerfile.build
  docker/Dockerfile.server
Labels: type:docker

#151 Jenkins unit tests
  Jenkinsfile
Labels: type:tests

#152 chore: tests for training with semantic masks
  Jenkinsfile
  docker/Dockerfile.build
  scripts/run_tests.sh
  tests/test_run_nosemantic.py
  tests/test_run_semantic_mask.py
Labels: type:tests

#135 Timm model projected feature extractor
  models/modules/projected_d/blocks.py
  models/modules/projected_d/discriminator.py
  models/modules/projected_d/projector.py
  options/base_options.py
Labels: type:rd, model:discriminator

#147 Choices options
  models/modules/classifiers.py
  models/networks.py
  options/base_options.py
  options/train_options.py
Labels: refactor

#153 fix: cyclegan semantic mask failure with f_s
  models/cycle_gan_semantic_mask_model.py
  tests/test_run_semantic_mask.py
Labels: bug

#154 feat: doc options auto update
  .github/workflows/github-actions-doc-options-update.yml
  .github/workflows/requirements_github_actions.txt
  models/modules/segformer/segformer_generator.py
  models/modules/segformer/utils.py
  scripts/generate_doc.py
Labels: documentation

#158 fix: tests with no cache
  scripts/run_tests.sh
Labels: type:tests

#166 doc: generate CLI documentation with categories
  docs/options.md
  options/base_options.py
  scripts/generate_doc.py
Labels: documentation

#162 feat: use the trained discriminator to rank generated images
  scripts/disc_single_image.py
Labels: model:discriminator, type:tools

#167 fix: install all requirements for github actions
  .github/workflows/github-actions-doc-options-update.yml
  .github/workflows/requirements_github_actions.txt
Labels: bug, documentation
