Repository jolibrain/joliGEN, pull requests merged in 2023-11, with the labels that each got.

#577 fix: load size for rectangular images, resize ref image for inference
  data/online_creation.py
  scripts/gen_single_image_diffusion.py
  tests/test_run_diffusion_online.py
  tests/test_run_semantic_mask_online.py
Labels: bug

#575 docs: tutorial BDD100K
  docs/source/_static/tutorial_bdd100k_day2night_inference_input.jpg
  docs/source/_static/tutorial_bdd100k_day2night_inference_result.jpg
  docs/source/_static/tutorial_bdd100k_inference-input.jpg
  docs/source/_static/tutorial_bdd100k_inference-result.jpg
  docs/source/_static/tutorial_bdd100k_training-curves.png
  docs/source/_static/tutorial_bdd100k_training-inference.png
  docs/source/_static/tutorial_bdd100k_training-segmentation.png
  docs/source/index.rst
  docs/source/tutorial_styletransfer_bdd100k.rst
  examples/example_tutorial_bdd100k.json
  scripts/bdd100k_to_joligen.py
Labels: documentation, ci:skip-tests

#579 Feat(script): GAN video inference
  docs/source/inference.rst
  scripts/gen_single_image.py
  scripts/gen_video_gan.py
Labels: documentation, ci:skip-tests

#581 feat(ml): dinov2 discriminator with registers
  models/modules/projected_d/projector.py
  options/base_options.py
Labels: model:discriminator, ready-for-review

#582 feat(ml): SigLIP based projected discriminators
  models/modules/projected_d/projector.py
  options/base_options.py
  tests/test_run_nosemantic.py
Labels: model:discriminator, ready-for-review
