Repository jolibrain/joliGEN, pull requests merged in 2023-06, with the labels that each got.

#430 feat: add psnr metric
  models/base_model.py
Labels: metrics

#414 feat: sam for mask refinement and edges
  docs/options.md
  models/base_diffusion_model.py
  models/modules/sam/sam_inference.py
  models/modules/utils.py
  models/palette_model.py
  options/base_options.py
  scripts/gen_single_image_diffusion.py
  util/mask_generation.py
  util/util.py
Labels: model:f_s, ready-for-review

#429 fix: bbox and mask for diffusion generation script
  data/online_creation.py
  scripts/gen_single_image_diffusion.py
Labels: ready-for-review

#426 feat: display test images
  models/base_model.py
  train.py
  util/visualizer.py
Labels: ready-for-review

#441 chore: datasets on joligen.com
  README.md
  scripts/run_tests.sh
Labels: documentation, data:datasets

#440 fix: mask and class conditioning in generation script
  scripts/gen_single_image_diffusion.py
Labels: ready-for-review, alg:diffusion

#444 fix: random offset missing in crop_image
  data/temporal_dataset.py
Labels: ready-for-review

#442 [Doc] Fix : rst headers format + typos + remove toc and hoverxref
  docs/source/choose.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/quickstart_ddpm.rst
  docs/source/quickstart_gan.rst
Labels: ready-for-review

#447 fix: resnet default number of blocks with diffusion
  models/palette_model.py
Labels: bug, model:generator, alg:diffusion

#454 fix: sample runs and default options
  README.md
  models/gan_networks.py
  options/base_options.py
  options/train_options.py
Labels: documentation

#457 chore(ci): skip-tests
  Jenkinsfile
Labels: ci:skip-tests

#451 feat(doc): datasets
  docs/source/dataloaders.rst
  docs/source/datasets.rst
Labels: documentation, ci:skip-tests

#448 Chore release script
  CHANGELOG.md
  package.json
  release.sh
Labels: ready-for-review, packaging, ci:skip-tests

#455 fix: visdom autostart and no display
  options/train_options.py
  train.py
  util/visualizer.py
Labels: display, ready-for-review

#456 chore: D_temporal to data_temporal options
  data/temporal_dataset.py
  models/base_gan_model.py
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
  models/gan_networks.py
  models/modules/projected_d/discriminator.py
  options/base_options.py
  tests/test_run_semantic_mask_online.py
Labels: api, ready-for-review

#465 Feat doc docker server
  docs/source/client.rst
  docs/source/docker.rst
  docs/source/index.rst
  docs/source/server.rst
Labels: documentation

#466 Feat doc tips
  docs/source/FAQ.rst
  docs/source/index.rst
  docs/source/server.rst
  docs/source/tips.rst
Labels: documentation

#463 chore: bump torch to 2.0.1
  requirements.txt
Labels: dependencies

#461 [doc] feat: page width at 75%
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation, ci:skip-tests

#417 feat: options for aspect ratio and augmentation of cond image
  scripts/gen_single_image_diffusion.py
Labels: ready-for-review

#469 API documentation
  .github/workflows/github-actions-doc-options-update.yml
  docs/source/API.rst
  docs/source/_static/api.html
  docs/source/_static/openapi.json
  scripts/generate_api_doc.sh
Labels: documentation, ci:skip-tests

#478 fix(doc): badly formatted title
  docs/source/choose.rst
Labels: documentation, ready-for-review, ci:skip-tests

#477 feat: diffusion inference with old and new models
  scripts/gen_single_image_diffusion.py
Labels: model:generator, ready-for-review, type:inference, alg:diffusion

#474 feat: option to choose metrics to compute
  models/base_model.py
  options/train_options.py
  util/metrics.py
Labels: metrics

#480 fix: cond inference
  models/palette_model.py
Labels: bug, type:inference, alg:diffusion, conditioning

#479 fix: save generated bbox only when useful in diffusion inference
  scripts/gen_single_image_diffusion.py
Labels: ready-for-review

#473 fix: rst autodoc + ci local testing
  .github/workflows/github-actions-doc-options-update.yml
  docs/source/conf.py
Labels: documentation, ready-for-review, ci:skip-tests

#483 Add doc badge on README
  README.md
Labels: documentation, ready-for-review

#487 chore: docker builds with cuda 11.8 / Ubuntu 22.04
  docker/Dockerfile.build
  docker/Dockerfile.devel
Labels: type:docker, ci

#489 fix: inference when no mask cond
  models/palette_model.py
Labels: bug

#485 fix: network loading
  models/base_model.py
Labels: bug, ready-for-review

#486 chore: server info call
  server/joligen_api.py
Labels: api, type:docker

#494 fix: help for diffusion inference script
  scripts/gen_single_image_diffusion.py
Labels: bug, ci:skip-tests
