Repository jolibrain/joliGEN, pull requests merged in 2023-10, with the labels that each got.

#555 feat(ml): optim weigth decay parameter control
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
  models/palette_model.py
  models/re_cycle_gan_semantic_mask_model.py
  options/train_options.py
  train.py
Labels: type:optimization

#528 fix: temporal discriminator with masks and bboxes
  Jenkinsfile
  data/base_dataset.py
  data/temporal_labeled_mask_online_dataset.py
  models/base_gan_model.py
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
  models/modules/UNet_classification.py
  scripts/run_tests.sh
  tests/test_run_semantic_mask_online.py
  train.py
Labels: bug, alg:gan, model:discriminator

#556 fix: save metrics plots and allow resuming
  util/visualizer.py
Labels: alg:evaluation

#557 doc: fix viton ddpm with reference image conditioning
  docs/source/_static/viton_ref_visdom.png
  docs/source/training.rst
Labels: documentation, ci:skip-tests

#559 fix: end of training metrics computation
  train.py
Labels: bug, model:metrics

#560 fix: save whole metrics_dict so we can reload it
  util/visualizer.py
Labels: bug

#561 fix: docker release script
  docker/Dockerfile.server
  docker/release_docker.sh
Labels: type:docker, ci:skip-tests

#562 fix: APA augmentation on multiple discriminators
  models/base_gan_model.py
  tests/test_run_nosemantic.py
Labels: bug, data:augmentation, model:discriminator

#563 feat: optimization eps value control
  models/base_model.py
  models/cut_model.py
  models/cycle_gan_model.py
  models/palette_model.py
  options/train_options.py
  train.py
Labels: type:optimization

#564 fix: init_metrics directory and metrics on CPU
  models/base_model.py
  train.py
Labels: bug, model:metrics

#566 chore: Pytorch 2.1 update
  data/base_dataset.py
  requirements.txt
Labels: dependencies

#565 chore: palette options help
  models/palette_model.py
Labels: documentation, ci:skip-tests

#558 feat: pix2pix task for palette
  data/aligned_dataset.py
  docs/source/dataloaders.rst
  docs/source/training.rst
  examples/example_ddpm_SEN2VEN.json
  models/palette_model.py
  scripts/gen_single_image_diffusion.py
  scripts/run_tests.sh
  tests/test_run_pix2pix_diffusion.py
Labels: ready-for-review, alg:diffusion

#569 fix(ml): inference for diffusion with reference image
  scripts/gen_single_image_diffusion.py
Labels: bug, alg:diffusion, alg:conditioning

#570 fix: amp for discriminators
  models/base_gan_model.py
  tests/test_run_semantic_mask_online.py
Labels: bug, enhancement

#572 chore: raise on missing semantic class
  data/online_creation.py
Labels: data:dataloader

#573 feat(ml): DinoV2 feature-based projected discriminator
  models/modules/projected_d/projector.py
  options/base_options.py
  tests/test_run_semantic_mask_online.py
Labels: model:discriminator
