Repository jolibrain/joliGEN, pull requests merged in 2024-03, with the labels that each got.

#620 fix: gan metrics reference
  models/base_model.py
Labels: bug, alg:gan, model:metrics

#621 fix: missing SSIM metric option
  options/train_options.py
Labels: documentation, model:metrics, ci:skip-tests

#622 fix: segformer generator for single channel inputs
  models/modules/segformer/backbone.py
  models/modules/segformer/segformer_generator.py
Labels: bug, model:generator

#623 fix: sam for single channel inputs
  models/modules/sam/sam_inference.py
Labels: model:discriminator

#624 fix: unet mha output for GANs
  models/modules/unet_generator_attn/unet_generator_attn.py
Labels: bug, alg:gan, model:generator

#625 fix: visualizer for mixed single and multi channel images
  util/visualizer.py
Labels: ci:skip-tests, output:viz

#629 chore: update black to 24.2.0
  .github/workflows/github-actions-black-formatting.yml
  data/__init__.py
  models/modules/classifiers.py
  models/modules/cm_generator.py
  models/modules/image_bind/imagebind_model.py
  models/template_model.py
  options/__init__.py
  requirements.txt
  scripts/bdd100k_to_joligen.py
  util/metrics.py
Labels: ready-for-review, ci:skip-tests

#626 fix: crash in inference script, errors in documentation
  data/image_folder.py
  docs/source/inference.rst
  options/base_options.py
  options/inference_diffusion_options.py
  scripts/gen_single_image.py
  scripts/gen_single_image_diffusion.py
  tests/test_run_mask_online_ref.py
  tests/test_run_mask_ref.py
  util/visualizer.py
Labels: bug, ready-for-review

#632 chore: remove run name for test metrics on visdom, to allows for comparisons
  util/visualizer.py
Labels: ci:skip-tests, output:viz

#630 feat(ml): HDiT for GANs
  models/base_model.py
  models/gan_networks.py
  models/modules/hdit/hdit.py
  tests/test_run_semantic_mask.py
Labels: alg:gan, model:generator

#633 chore: do not save images used to compute metrics as default
  models/base_model.py
  options/train_options.py
  train.py
Labels: enhancement

#636 fix: supervised loss for aligned GANs, with unit tests
  models/cut_model.py
  scripts/run_tests.sh
  tests/test_run_pix2pix_gan.py
Labels: bug, alg:gan

#634 feat(ml): consistency models for pix2pix
  models/cm_model.py
  models/diffusion_networks.py
  models/modules/cm_generator.py
  tests/test_run_cm.py
Labels: alg:diffusion, alg:consistency_model

#615 fix: potential bug in gen_single_diffusion model path
  scripts/gen_single_image_diffusion.py
Labels: bug, ready-for-review

#637 DISTS supervised loss
  models/cut_model.py
  requirements.txt
Labels: alg:gan, nn:loss

#640 fix: show full test set output with GANs
  models/base_model.py
  models/cut_model.py
Labels: alg:gan

#642 fix: GAN semantic visual output
  models/base_model.py
Labels: bug, alg:gan

#638 feat(ml): min-SNR loss weight for diffusion, 2303.09556
  models/modules/diffusion_generator.py
  models/palette_model.py
  tests/test_run_diffusion.py
Labels: alg:diffusion
